# Generated by Django 4.2.30 on 2026-07-08 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='FoodExperience',
            fields=[
                ('food_experience_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price_sgd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Inactive', 'Inactive')], default='Draft', max_length=30)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='food_experiences', to='experiences.category')),
            ],
            options={
                'db_table': 'food_experience',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Available', max_length=30)),
                ('food_experience', models.ForeignKey(db_column='food_experience_id', on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='experiences.foodexperience')),
            ],
            options={
                'db_table': 'timeslot',
            },
        ),
        migrations.AddField(
            model_name='foodexperience',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='food_experiences', to='experiences.location'),
        ),
        migrations.AddField(
            model_name='foodexperience',
            name='vendor_profile',
            field=models.ForeignKey(db_column='vendor_profile_id', on_delete=django.db.models.deletion.CASCADE, related_name='food_experiences', to='vendors.vendorprofile'),
        ),
    ]
