# Generated by Django 4.2.30 on 2026-07-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('itinerary_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itinerary',
            },
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('itinerary_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.IntegerField(blank=True, null=True)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('planned_time', models.TimeField(blank=True, null=True)),
                ('food_experience', models.ForeignKey(db_column='food_experience_id', on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_items', to='experiences.foodexperience')),
                ('itinerary', models.ForeignKey(db_column='itinerary_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itinerary.itinerary')),
            ],
            options={
                'db_table': 'itinerary_item',
            },
        ),
    ]
