# Generated by Django 4.2.30 on 2026-07-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('vendor_profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('contact_number', models.CharField(max_length=30)),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('business_address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_profile',
            },
        ),
    ]
